<a href="https://colab.research.google.com/github/rozmar/Analyzing-Open-Neuroscience-Data-SZTE-2027/blob/main/Modul%201/Gyakorlo_feladatok_03_NumPy_alapok.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy alapok - gyakorló feladatok

## 1. Feladat
<div class="exercise" style="background: #DFF0D8; border-radius: 3px; padding: 10px; color: #000;">
<p>
Írj egy függvényt, aminek van egy <i>n</i> paramétere. A függvény adjon vissza egy <i>n</i> méretű NumPy tömböt, amiben egész számok vannak 1-től n-ig (maga az n is szerepeljen), véletlen sorrendben. Minden szám pontosan egyszer szerepeljen. Például az alábbi kód futtatása után<br />
<pre>
arr = permutation(5)
print(arr)
</pre>
egy lehetséges eredmény:
<pre>
[1 3 2 4 5]
</pre>
</p>
<p><b>Tipp:</b> Ez a feladat megoldható a <code>random</code> és a <code>numpy.random</code> modullal is. Mindkettő megfelelő, de a végeredmény mindenképp egy numpy array legyen.</p>
</div>

## 2. Feladat
<div class="exercise" style="background: #DFF0D8; border-radius: 3px; padding: 10px; color: #000;">
<p>
Generálj egy <code>M</code> nevű, <code>5 x 5</code> méretű, numpy array-t, ami normál eloszlásból származó véletlen számokat tartalmaz. Ezután készíts egy új, <code>U</code> nevű, szintén <code>5 x 5</code> méretű, numpy array-t, ami az <code>M</code> tömb jobb felső részét tartalmazza. Azaz, az új tömb átlójában és felette ugyanazok a számok szerepeljenek, az átló alatt pedig csupa 0 érték legyen. Például, ha az <code>M</code> így néz ki:
<pre>
-0.58  1.16  1.17  0.04  1.34
 1.89 -1.91 -0.22  1.85 -0.62
-2.01 -0.50  1.47 -0.49 -2.19
 0.48  0.85  0.99  0.53  1.45
-1.24 -0.55  0.07  0.30 -0.24
</pre>
akkor az <code>U</code> ilyen lesz:
<pre>
-0.58  1.16  1.17  0.04  1.34
 0.00 -1.91 -0.22  1.85 -0.62
 0.00  0.00  1.47 -0.49 -2.19
 0.00  0.00  0.00  0.53  1.45
 0.00  0.00  0.00  0.00 -0.24
</pre>
Írasd ki egymás után a két tömböt.
</p>
<p><b>Megjegyzés:</b> A fenti példában az átláthatóság kedvéért két tizedesjeggyel írtam ki a számokat, a megoldásban elég csak alapértelmezett <code>print</code> függvényt használni.</p>
<p><b>Tipp:</b>A feladat megoldásában használhatsz <code>for</code> ciklust, de ahol lehet, próbáld kihasználni a numpy előnyeit (pl. slicing).</p>
</div>

## 3. Feladat
<div class="exercise" style="background: #DFF0D8; border-radius: 3px; padding: 10px; color: #000;">
<p>Generálj egy <code>M</code> nevű <code>4 x 5</code> méretű  kétdimenziós numpy tömböt, amiben 0 és 1 közötti véletlen valós számok vannak. Ezután generálj véletlenszerűen egy sorindexet (<code>i</code>) és egy oszlopindexet (<code>j</code>). Írd ki a tömb <code>i.</code> sorát, a <code>j.</code> oszlopát és végül az <code>i, j</code> indexen lévő elemet. Például, ha a tömböd
<pre>
0.12 0.75 0.43 0.23 0.89
0.67 0.44 0.52 0.99 0.76
0.06 0.17 0.57 0.78 0.44
0.07 0.91 0.45 0.32 0.22
</pre>
és a <code>i</code> értéke 1, a <code>j</code> értéke pedig 4, akkor kiíratás után ezt kapod:
<pre>
[0.67 0.44 0.52 0.99 0.76]
[0.89 0.76 0.44 0.22]
0.76
</pre>
A feladatot ciklus használata nélkül oldd meg.
</p>
<p><b>Tipp 1:</b> A tömb indexei csak pozitív egész számok lehetnek, 0-val kezdődik az indexelés.
</p>
</div>

## 4. Feladat
<div class="exercise" style="background: #DFF0D8; border-radius: 3px; padding: 10px; color: #000;">
<p>Generálj egy <b>10</b> elemű, egydimenziós numpy tömböt. A neve legyen <code>values</code>, 0 és 50 közötti véletlen egész számokat tartalmazzon. Készíts egy második, szintén <b>10</b> elemű, egydimenziós numpy tömböt, aminek a neve <code>level</code>. Ez 0 és 1 közötti véletlen valós számokat tartalmazzon.<br />
Számítsd ki és írd ki a <code>values</code> tömb azon elemeinek az átlagát, amelyeknél a <code>level</code> tömbben lévő érték nagyobb, mint 0.5. <br />
Például, ha<br />
<code>values = [15 16 22 23 30  6 23 20 14 42]</code><br />
<code>level = [0.82 0.13 0.85 0.55 0.05 0.64 0.30 0.43 0.23 0.87]</code><br />
Akkor az eredmény<br />
<code>21.6</code>
</pre>
</p>
<p>A feladatot ciklus használata nélkül oldd meg.</p>
</div>

## 5. Feladat
<div class="exercise" style="background: #DFF0D8; border-radius: 3px; padding: 10px; color: #000;">
<p>Generálj egy <code>5 x 5</code> méretű kétdimenziós numpy tömböt, amiben véletlen egész számok vannak 1 és 10 között. Számítsd ki a teljes tömb átlagát és szórását, ezeket tárold el egy-egy változóban. Ezután alakítsd át a tömbödet úgy, hogy minden elemből kivonod az előbb megkapott átlagot, majd elosztod a szórással. Írd ki az eredeti tömböt, az átlagot és a szórást, valamint az átalakított tömböt.
Például, ha a tömb
<pre>
[[10  2  6  4  2]
 [ 4  6  6  7  2]
 [ 9  3  5  9  5]
 [ 2  6  3  5  9]
 [10  4  8  5  2]]
</pre>
akkor kiírás után az alábbiakat kapjuk
<pre>
5.36
2.5904439773907484
[[ 1.79119874 -1.29707495  0.2470619  -0.52500653 -1.29707495]
 [-0.52500653  0.2470619   0.2470619   0.63309611 -1.29707495]
 [ 1.40516453 -0.91104074 -0.13897232  1.40516453 -0.13897232]
 [-1.29707495  0.2470619  -0.91104074 -0.13897232  1.40516453]
 [ 1.79119874 -0.52500653  1.01913032 -0.13897232 -1.29707495]]
</pre>
A megoldást ciklus használata nélkül, vektorizált műveletekkel valósítsd meg.
</p>
</div>